### ISSUE TITLE
Rename respondWith* to on*

### ISSUE THREAD

**Issue by afontcu** [holaluz/nuxt-clean#10]
We were discussing with @edufarre that `respondWithSuccess` is more verbose than `onSuccess`, and also it presents a callback from the wrong standpoint: not from the consumer, but from the function providing the callback.

When I write a Vuex action that triggers a use case, I want to do something "on success" <-- focus on the consumer
When I write a use case, I want something to let caller know that it should "respond with success" <-- focus on the caller (provider).

I do believe it makes sense to focus on the consumer, thus the suggesion.

It looks like a "big" modification, but it's just a matter of search&replace (`respondWith` -> `on`). 

As said, it is also shorter and faster to type 🤷

**Comment by edufarre** [comment]
Shall we move forward this new notation? 🙏 

I definitely believe it would be much better than the current one, and shorter too.
