### ISSUE TITLE
How to handle UI validation?

### ISSUE THREAD

**Issue by afontcu** [holaluz/nuxt-clean#8]
One of the common use cases in UI applications is to validate UI data such as forms. Usually, this validation comes from business rules ("password cannot be shorter than 8 chars", "email must be from a valid provider").

As we know, business rules should live in the "business side" of our app: The domain/application layers.

Questions:

* What's the best way to handle these validations when used along with tools such as [vuelidate](https://vuelidate.js.org/), [veevalidate](https://logaretm.github.io/vee-validate/)…?
* Do we need these tools?
* How can we express these validations (for example, using Value Objects)?
* Can we leverage the `Result` class here, too, to make everything more expressive and flexible?

I'd say a sensible flow would be:

`user types a value / blurs from an input` -> `validator tool triggers a use case (something like createPassword?` -> `if use case succeeds, everything's ok. if use case fails, display error message`.

However, I'm not sure how verbose/complex this might become, defeating its purpose.

**Comment by edufarre** [comment]
I'm working on it, I'll get back to you once I've got some workaround
